---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wahyu prayudo.
--- DateTime: 04/10/2019 7:01
---

local _comManager = {}

local Table = require('orm.class.table')
local _comTable = Table("companies")



_comManager.getCompanies = function (callback)
    callback(_comTable.get:all():getPureData())
end

_comManager.parseTable = function (responseStr,callback)
    local t = cjson.decode(responseStr)
    -- local comTable = _comTable
    local ret = {}
     -- if t  > 0  then
    --    comTable.get:delete()
        for i,v in pairs(t) do
      --      local t = {}
            table.insert(ret,
                    {address = v[1],
            zip = v[2],
            city = v[3],
            slug = v[4],
            state = v[5],
            contact = v[6],
            account = v[7]})
           -- local companies = comTable(t)
          --  companies:save()
          --  table.insert(ret,companies:getPureData())
        end
     -- end
    if callback then
        callback(ret)
    end
end

_comManager.loadCompanies = function (callback)
--Lihat alamat IP di IP wireless

    lua_http.request({ url  = "http://192.168.0.5:8090/companies/get",
                       onResponse = function (response)
                           if response.http_code ~= 200 then
                               if callback then
                                   callback(nil)
                               end
                           else
                               lua_thread.postToThread(BusinessThreadLOGIC,"Companies","parseTable",response.response,function(data)
                                   if callback then
                                       callback(data)
                                   end
                               end)
                           end
                       end})
end

return _comManager
